// Mock data for demonstration
export const MOCK_VAULTS = [
  {
    vaultId: '1',
    name: 'Stable Yield Pro',
    strategy: 'stablecoin' as const,
    totalDeposits: 1250000,
    currentAPY: 6.8,
    performanceFee: 0.3,
    rebalanceFrequency: 'weekly' as const,
    description: 'Auto-optimized stablecoin vault across Aerodrome, Uniswap V3, and Curve',
  },
  {
    vaultId: '2',
    name: 'Blue Chip Growth',
    strategy: 'bluechip' as const,
    totalDeposits: 890000,
    currentAPY: 12.4,
    performanceFee: 0.3,
    rebalanceFrequency: 'weekly' as const,
    description: 'ETH, WBTC, and top Base tokens with automated rebalancing',
  },
  {
    vaultId: '3',
    name: 'Microcap Hunter',
    strategy: 'microcap' as const,
    totalDeposits: 340000,
    currentAPY: 24.7,
    performanceFee: 0.3,
    rebalanceFrequency: 'weekly' as const,
    description: 'Community-curated emerging tokens with safety checks',
  },
];

export const MOCK_TOKENS = [
  {
    address: '0x1234...5678',
    symbol: 'NOVA',
    name: 'Nova Protocol',
    marketCap: 8500000,
    launchDate: new Date('2024-01-15'),
    safetyScore: 85,
    trendingScore: 92,
    priceChange24h: 12.4,
    logo: '🌟',
  },
  {
    address: '0x2345...6789',
    symbol: 'FLUX',
    name: 'Flux Finance',
    marketCap: 4200000,
    launchDate: new Date('2024-02-01'),
    safetyScore: 72,
    trendingScore: 78,
    priceChange24h: -3.2,
    logo: '⚡',
  },
  {
    address: '0x3456...7890',
    symbol: 'APEX',
    name: 'Apex DAO',
    marketCap: 12000000,
    launchDate: new Date('2023-12-10'),
    safetyScore: 91,
    trendingScore: 88,
    priceChange24h: 8.7,
    logo: '🔺',
  },
];

export const MOCK_POOLS = [
  {
    address: '0xabcd...ef01',
    chain: 'base' as const,
    token0Symbol: 'USDC',
    token1Symbol: 'USDbC',
    safetyScore: 95,
    liquidityLockPercent: 100,
    auditStatus: 'audited' as const,
    lastScannedAt: new Date(),
    tvl: 5400000,
    volume24h: 890000,
  },
  {
    address: '0xbcde...f012',
    chain: 'base' as const,
    token0Symbol: 'ETH',
    token1Symbol: 'WBTC',
    safetyScore: 88,
    liquidityLockPercent: 85,
    auditStatus: 'audited' as const,
    lastScannedAt: new Date(),
    tvl: 12000000,
    volume24h: 2400000,
  },
];
